name: country-stability
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython=8.10.0
  - dask=2023.6.0
  - dask-labextension=6.1.0
  - geopandas=0.12.2
  - geos=3.11.1 
  - gdal=3.6.2 
  - geoplot=0.5.1 
  - georasters
  - ipyparallel=8.4.1
  - jupyter=1.0.0
  - jupyterlab=3.5.3
  - jupyter_contrib_nbextensions
  - mapclassify
  - matplotlib
  - matplotlib-base
  - nodejs
  - numpy
  - nb_conda_kernels=2.3.1
  - nbclassic=0.5.1 
  - nbclient=0.7.2 
  - nbconvert=7.2.9 
  - openpyxl
  - pandas
  - pandas-datareader
  - plotly
  - pip
  - pycountry
  - pyproj
  - requests
  - scipy
  - seaborn
  - shapely
  - scikit-learn
  - stata_kernel
  - statsmodels
  - unidecode
  - xlrd
  - pip:
    - geonamescache 
    - linearmodels 
    - isounidecode 
    - geocoder 
    - stargazer
