name: EconGrowthUG
channels:
  - conda-forge
  #- mro
  - r
  #- defaults
dependencies:
  - r-base
  - r-dplyr
  - r-fields
  - r-tibble
  - python=3.10
  - plotly
  - r-classint
  - r-magick
  - r-rcolorbrewer
  - r-tidyr
  - kiwisolver
  - r-tigris
  - geoplot
  - xlrd
  - matplotlib-base
  - r-gridgraphics
  - r-readxl
  - ipywidgets
  - r-stringr
  - jupyter
  - pygeos
  - r-ggmap
  - r-fixest
  - r-ggplot2
  - stata_kernel
  - jupyterlab#=3.4.4
  - georasters
  - r-broom
  - r-haven
  - r-plotly
  - ipython
  - scipy
  - r-rgeos
  - r-lazyeval
  - ipykernel
  - pycountry
  - statsmodels
  - nltk
  - r-pacman
  - jupyter_nbextensions_configurator
  - pandas
  - r-rgdal
  - matplotlib
  - r-raster
  - r-rnaturalearth
  - r-ggrepel
  - networkx
  - r-plot3d
  - r
  - geotiff
  - r-ggnewscale
  - geopy
  - ipyparallel
  - r-devtools
  - spyder
  - r-tidyverse
  - ipython_genutils
  - r-magrittr
  - spatialpandas
  - scikit-learn
  - nodejs
  - r-ggthemes
  - jupyterlab-markup
  - r-dagitty
  - r-sp
  - seaborn
  - nb_conda_kernels
  - r-rnaturalearthdata
  - r-irkernel
  - r-cowplot
  - geopandas
  - scikit-image
  - pandas-datareader
  - geocoder
  - nbgrader
  - openpyxl
  - python-kaleido
  - ghostscript
  - camelot-py
  - plotnine
  - html5lib
  - pip
  - pip:
    #- abc-classroom==0.1.9
    - geonamescache#==1.5.0
    - github3-py#==3.2.0
    - RISE
    - git+https://github.com/ozak/google-drive-downloader
    - git+https://github.com/ozak/camelot
    - jupyter_contrib_nbextensions
    - stargazer
    #- jupyterlab-imarkdown==0.2.0
    - jupyterlab-markup-expr#==0.1.1
    - keplergl#==0.3.2
    - pyjwt#==2.4.0
    - ruamel-yaml#==0.17.21
    - ruamel-yaml-clib#==0.2.6
    - traittypes#==0.2.1
    - uritemplate#==4.1.1
    - nbgitpuller
    - rdrobust 
    - pyfixest 
    - lets-plot 
    - jupyterlab_myst
